### ISSUE TITLE
Switch between source/header

### ISSUE THREAD

**Issue by Shatur** [autozimu/LanguageClient-neovim#1021]
## Is your feature request related to a problem? Please describe.

In C++ often need to switch between header and source file. Clang implements [Switch between source/header extension](https://clangd.llvm.org/extensions.html#switch-between-sourceheader).

## Describe the solution you'd like

I suggest to add a support for this extension as a separate plugin.

## Additional context

For example, asycomplete.vim have the [following plugin](https://github.com/micchy326/vim-lsp-clangd-switch).

**Comment by martskins** [comment]
I opened #1072 a few days ago where I propose (as an alternative to that PR) to create a set of extensions for LCN and make it so that it's easier to extend functionality specific to some language server.
I would argue that it's better to wait for a reply on the extension topic on the PR I merged, as to not introduce any breaking changes if we were to move to an extension paradigm later on. But if that doesn't happen, we can always bake those clang specific requests into the client.

**Comment by martskins** [comment]
@Shatur95 Just opened #1105 to address this. Tested it locally and it seems to work, if you could checkout that PR and compile LCN from source and try it out yourself it would be great.

Also, sorry for taking so long to solve this.

**Comment by Shatur** [comment]
Sorry, I switched to VSCode with Neovim as a backend :(
So, I use Neovim as a text editor and VSCode when I need an IDE.

**Comment by martskins** [comment]
I'll close this one then but I'm keen to merge that PR so if you ever come back to LCN it will be there waiting for you 😄
