### ISSUE TITLE
Adopt rust conventions

### ISSUE THREAD

**Issue by martskins** [autozimu/LanguageClient-neovim#1049]
I know this is a highly opinionated issue, but how would you feel about adopting more rust conventions such as using snake case variable names, screaming snake case const names, or importing only the necessary modules (this is more of a good habit rather than a convention). I think there's value in doing this, especially the last one, as it will be clearer where things are being imported from, and I think newcomers to the project would appreciate that.

This would only apply for the rust files obviously, every vim file would be left untouched. If you think there's value in this I can open a PR, it shouldn't be too difficult and I think it should be pretty safe too, I doubt we'll encounter any surprises.

Again, I know this is highly subjective, so I'm ok with whatever the answer is, but I do believe there's value in adopting conventions and good practices where possible.

**Comment by autozimu** [comment]
Totally agree actually.

Part of the historical reason of such naming is to keep close to LSP method names so that it can be easier to lookup. But turns out not so useful in reality. Keyword lookup is sufficient in majority cases.

Free free to create PR(s).

BTW, if you want to have write access to this repo, just reply back here. I noticed you're making more contributions in the past few months. Really appreciate it.

**Comment by martskins** [comment]
Opened #1050 to address this. :smile: 

About write access, I would love to, I think we could do some cleanup of old issues and I would love to be able to help move this forward. This plugin is a major part of my day to day as a developer, so I really would love to try and give something back. :+1:

**Comment by autozimu** [comment]
Awesome!

I have just invited you access to this repo.
