### ISSUE TITLE
Refactorins suggestions

### ISSUE THREAD

**Issue by purpleP** [autozimu/LanguageClient-neovim#125]
I will make a pull request for all refactorings that you will approve. Note that I haven't dig deep, so maybe this suggestions are useless and you've already know and considered all that.

1. `Sign.py`
First of all module names should be in snake case. I suggest using `Sign = collections.namedtuple('Sign', lign, signname, bufnumber)`.

2. `state.make_serializable`. Why do you need that? If you want to dump all primitive types, and skip everything that isn't json serializable by default you can use `json.dumps(obj, skipkeys=True)`
Also the current implementation represents non primitive object with `None`, but `None` is serializable, so you will exclude `None` from the copy you're making
```
v = make_serializable(v)
if v is None:
     continue
...
try:
    json.dumps(d)
    return d
except Exception:
    return None
```

3. `DiagnosticsDisplay.py` and `CompletionKind.py`. Again, snake_case in module names and it's generally non-pythonic to use module to only define one class or structure. In Java it's a rule in python it's a thing to avoid.
But anyway, dictionaries are pretty compact and fast in python 3.6, but still I think it makes sense to use `tuple` her e and then just add one when you will index it.

4. https://github.com/autozimu/LanguageClient-neovim/blob/master/rplugin/python3/LanguageClient/TextDocumentItem.py#L18
```
        changes = []  # type: List[Dict]
        changes.append({
            "text": newText
        })
        self.text = newText
        return (self.incVersion(), changes)
```
Why not

```
self.text = new_text
return self.inc_version(), [{'text': new_text}]
```
Because of python good expressiveness people like Raimond Hettinger says that generally there should be one english sentence in one line on python code. I don't see the point of breaking this so much, making a variable and then appending to it.

5. Use more modern `pathlib` instead of `os.path` in `util.py` to make code more consice and expressive.
You can do things like
```
Path('/tmp') / 'some'
Path('/tmp').exists()
Path('/tmp').is_dir()
```
6. Use keyword arguments instead of passing dictionary in `update_state`.
7. For performance you can change 
```
qftype = {
            1: "E",
            2: "W",
            3: "I",
            4: "H",
}[severity]
```
Into
```
qftype = ('E', 'W', 'I', 'H')[serverity - 1]
```
@autozimu 
You can also extract this into instance variable to avoid creating it every time or use `enum.Enum`. Diagnostics stuff should probably be `Enum` to.

8.
```
In [7]: %%timeit
   ...: if isinstance(j, str):
   ...:     b = int(j)
   ...:
339 ns ± 0.22 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [8]: %timeit b = int(j)
238 ns ± 0.124 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

So [this](https://github.com/autozimu/LanguageClient-neovim/blob/master/rplugin/python3/LanguageClient/RPC.py#L85) doesn't make sense. You can just use `int(message['id'])`.

9. Decorators. Use `functools.wraps`. Also you might consider using this trick.
https://github.com/autozimu/LanguageClient-neovim/blob/master/rplugin/python3/LanguageClient/LanguageClient.py#L23

```
def decorator(func, some, decor, arguments):
     if not func:
          return partial(decorator, decor=decor, arguments=arguments)
     @functools.wraps
     def wrapper(*args, **kwargs):
...
```
Now you can remove additional wrapper to pass decorator arguments.

**Comment by autozimu** [comment]
1. 

> First of all module names should be in snake case

I agree with this. For the latter part though, I'd like to keep current class implementation instead of namedtuple.

2. 

> json.dumps(obj, skipkeys=True)

This simply doesn't work. That's why I make my own serialization function.

3. I agree with the filename change. But Tuple is not that great when we need to exchange data with neovim/vimscript.

4. Nice catch.

5. Looks good to me.

6. Looks good but not practical. Sometimes we need to update a deep nested property.

7. Agree qftype should be extracted into const variable or enum. But not DiagnosticsDisplay, as I mentioned before, it will needed to seamlessly convert between neovim/vimscript.

8. 👍 

9. Good to know.

**Comment by purpleP** [comment]
@autozimu 
>  I'd like to keep current class implementation instead of namedtuple.
Why? Just curious, because again, maybe you know, maybe you don't, but namedtuple is more space efficient and provides faster attribute access, but I heard that it takes about 1 ms to create it (the class, not the instance of it). So it will make startup time at most 1 ms slower...

> This simply doesn't work
The suggestion that I gave about using `skipkeys` is wrong, however `skipkeys` works. It just does what it says it does, it skips the keys, not the values.
In any case default serializable types are known from python documentation. So you can just use `isinstance(obj, (dct, list, tuple, int, float, str, NoneType))` to check if it is serializable. Unless you're monkeypatching `json.dumps` using `try json.dumps(obj) except` is a waste of time.
You can also try to use typehints to deserialize objects. It's doable, but would require a bit of code and I'm not sure how stable the internal apis of `typing` module. You can use type hints from `__init__` signature and then if you would extract things like `int` from `List[int]` you could turn dicts into custom objects.

**Comment by autozimu** [comment]
I don't want the change because there isn't any real benefits by making the changes except it being a different approach to achieve the same task, needless to say the potential startup latency.

If you want to make contribution to this project, why don't adding more test coverage and integration tests as you've already discovered instead of nit-picking small syntax difference? Or if you really want make the small syntax changes, why don't make the changes instead of keep spending more time arguing which one is better than the other? If you do concern a big PR containing lots of changes will get rejected because of part the change, it's because you are doing it wrong. Start by something small, build your reputation gradually, then you will earn your trust.

**Comment by purpleP** [comment]
@autozimu Um... well I'm not interested in earning anyones trust. I don't think that pull requests should be accepted because you trust someone. They should be accepted if the code quality is acceptable. If I will have time I'll try to make more general improvements if I could.
