### ISSUE TITLE
Getting false issues in tsx files wherever JSX is used

### ISSUE THREAD

**Issue by rsimp** [autozimu/LanguageClient-neovim#137]
Currently I have errors listed anywhere I use JSX in my tsx files: 
"Cannot use JSX unless the '--jsx' flag is provided."

In my tsconfig.json:
```
{
  "compilerOptions": {
    "jsx": "react"
    ...
  }
}
```

**Comment by DeltaEvo** [comment]
I don't understand how this issue is about LanguageClient-Neovim, can you describe a little more your issue please ?

**Comment by autozimu** [comment]
This is issue with language servers. Please file bug at their corresponding repos.

Also, I think the problem is highly possible a configuration one. I've been using `javascript-typescript-langserver` for tsx for quite some time, and haven't seen this problem. If you want to have an example, here is one, <https://github.com/autozimu/react-boilerplate>.
