### ISSUE TITLE
Silent Startup Option

### ISSUE THREAD

**Issue by still-dreaming-1** [autozimu/LanguageClient-neovim#145]
Is there a way to make the startup silent? Every time I start nvim it shows a bunch of stuff being buffered at the bottom for a while. If I try to type a command, it gets in the way. Sometimes I start and stop nvim frequently for, reasons. I do not want to have to disable auto start, I want it to auto start, silently. It would also be nice if there was some indication of when it had finished, but I'm not really sure what I would want that to be...

**Comment by autozimu** [comment]
Can you paste here what the messages you are seeing?

**Comment by still-dreaming-1** [comment]
The startup ones about which files it is parsing and stuff like that.
Example: `[Log] Parsing file:///myFilePath.php`

**Comment by still-dreaming-1** [comment]
Ah, brain fart... Of course that is not directly from this plugin... It is more directly from this one:
https://github.com/roxma/LanguageServer-php-neovim
 Anyway, what are your thoughts on this?

**Comment by autozimu** [comment]
Fundamentally, the issue is because some concept of VSCode does not map perfectly to vim/neovim. These messages are sent by language servers method `window/logMessage`. In VSCode, the messages are just logged in a log buffer without bothering user, while in vim/neovim, we don't have such dedicated mechanism. The only similar way of handling this event is `echomsg`, which as you've already found, might be too much and annoying.

I will push a new commit shortly to introduce a config `LanguageClient_windowLogMessageLevel`  such that non important `window/logMessage` will not trigger a `echomsg`.

**Comment by still-dreaming-1** [comment]
Thanks! That already made those messages go away.
