### ISSUE TITLE
Why rust?

### ISSUE THREAD

**Issue by wsdjeg** [autozimu/LanguageClient-neovim#218]
@autozimu Hi, thanks for your plugin ,but any reason why use rust rewrite this plugin? most people do not has rustc installed in computer.  can not find any info about rust dependence in readme.

and I also find this is not a remote plugin now.

**Comment by DeltaEvo** [comment]
I'm not sure about that (@autozimu need to confirm):

- Rust rewrite started after that some Mac users wanted to have this plugin compatible with python 2 because they don't have python3 by default (#184, #162)
- This is a "Remote Plugin", but not in the same way than Neovim's Remote Plugins, a remote process is spawned with job api and neovim/vim talk with it. So this plugin is fully supported by vim and Neovim
- If you dont have Rust installed some binaries are compiled automatically https://github.com/autozimu/LanguageClient-neovim/releases and if you want to build from source getting rustc is very easy http://rustup.rs/

\<fanboy\>For me the Rust rewrite is not a bad thing because Rust = ❤️ \</fanboy\>

**Comment by autozimu** [comment]
Sorry, has been in travel this week.

@DeltaEvo has answered this question reasonably well. Closing.

**Comment by DerWeh** [comment]
I would be still curious why you use rust. I don't see how an answer was provided. The argument seems to be some Mac users don't have Python by default. I don't see how switching to Rust, which no one has by default helps this problem.

What are the advantages? I assume it is because Rust is faster than Python?

Personally I still use the old master branch as it runs out of the box. The next branch is way too cumbersome to set up and unstable.

**Comment by wsdjeg** [comment]
we are still using the fork in spacevim https://github.com/SpaceVim/LanguageClient-neovim

**Comment by autozimu** [comment]
> way too cumbersome to set up and unstable

What do you mean by this?

If there is a bug, please file an issue.

As the end user, the prebuilt binaries should be sufficient. How come it is "cumbersome"? If you are using a platform that is not covered by prebuilt binaries, please also file an issue.

**Comment by autozimu** [comment]
> different branch

That's not different branch, they are simply different tags.

They're in different tags simply because putting all prebuilt binaries together is not practical. Each binary is around 10M, and currently there are 5 platform binaries, and there might be more in future.

If you are planning integrate this package into distribution, you can use https://github.com/autozimu/LanguageClient-neovim/releases to get all prebuilt binaries and dynamically pick the binary based on current platform.

Also, the python implementation is still in branch master of this repo and is still accepting PRs. I don't see too much point in linking your own outdated fork here.

**Comment by wsdjeg** [comment]
I do not see the python branch in the home page. sorry.

**Comment by wsdjeg** [comment]
I think the python branch should be linked in the readme. I just think you have override the python implement. so I fork it.

**Comment by autozimu** [comment]
Good point. Will make that shortly.

**Comment by DerWeh** [comment]
> > way too cumbersome to set up and unstable
> 
> What do you mean by this?
> 
> If there is a bug, please file an issue.
> 
> As the end user, the prebuilt binaries should be sufficient. How come it is "cumbersome"? If you are using a platform that is not covered by prebuilt binaries, please also file an issue.

Concerning the instability, yes I think there are still plenty of bugs, sadly I currently have no time to file sufficient issues as I have a lot of deadlines currently. For most of the crashes I experienced there were already open issues, they might be fixed by now. As I said, I currently don't have enough time. My experience was just that after switching to `next` it permanently crushed in combination with `pyls`.

It is "cumbersome" as the integration with plug-in managers seems to still be work-in-progress. I think the preferred method was just changed once again as there were issues.
Furthermore, it is not allowed to download \`untrusted' binaries in some environments.

This is all is not that much of a problem, I was mainly interested what the advantage of using `rust` is, as I don't know any.
