### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by NickeZ** [autozimu/LanguageClient-neovim#29]
Do you think it would be a good idea/possible to implement some sort of timer. I think a timeout of 0.5 seconds or something would decrease the amount of data sent back and forth to the language server. I'm thinking that the timout gets reset every time you use the keyboard.

**Comment by autozimu** [comment]
I've actually included that functionality previously, but it didn't work out very well.

The messages sent to language servers mostly are notifications of change/save. Language clients will send completion request from time to time. If the notifications are delayed, the completion result will be out of sync and become useless for the user.

From the other point of view, language server should and can handle these amount of messages efficiently considering today's CPUs. In rare case of language server cannot handle those messages promptly, it is always much easier to optimize the language server side instead of the client side.
