### ISSUE TITLE
Cquery highlight support?

### ISSUE THREAD

**Issue by ghost** [autozimu/LanguageClient-neovim#299]
Is there a plan for supporting cquery highlight?

**Comment by autozimu** [comment]
What highlight are you referring to?

If it is compiling error like highlights, it’s already supported, but only
in neovim.

**Comment by ghost** [comment]
@autozimu 
Cquery implement feature of semantic highlighting
Is there a plan to support it?

![screenshot_20180127_160142](https://user-images.githubusercontent.com/20379044/35470031-51f7cb4a-037c-11e8-93de-829817a2264d.png)

**Comment by autozimu** [comment]
@MaskRay Were you able to point to some docs detailing this API?

**Comment by MaskRay** [comment]
Here the issue is that aside from generic language client framework (e.g. LanguageClient-neovim lsp-mode), there should be language server-specific plugins for different language servers, because servers may provide extensions or need adaptation.

See https://github.com/emacs-lsp for a list of language-specific plugins in the Emacs land.

I learned that Vim/Neovim `matchaddpos()` is very limited and only supports a small number of overlays (8).

If someone decides to implement it, the response messages is defined in https://github.com/cquery-project/cquery/blob/master/src/message_handler.h#L27 and here is an example:

* `stableId`: identifier
* `SymbolKind parentKind`: the client may use it to differentiate global variables with local variables. No clients has exploited this information yet.
* `ClangSymbolKind kind`: similar with LSP `namespace SymbolKind`, but Clang specific. This is used to differentiate methods/functions/variables/namespaces/...  I didn't use LSP `SymbolKind` because it misses: `ClassMethod,StaticMethod,  InstanceProperty,  ClassProperty,  StaticProperty, Destructor, ConversionFunction`.
* `StorageClass storage`: static / auto / none. Can be used to differentiate static variables vs global variables.

```json
{
  "jsonrpc": "2.0",
  "method": "$cquery/publishSemanticHighlighting",
  "params": {
    "uri": "file:///tmp/c/a.cc",
    "symbols": [
      {
        "stableId": 6,
        "parentKind": 3,
        "kind": 13,
        "storage": 1,
        "ranges": [
          {
            "start": {
              "line": 10,
              "character": 18
            },
            "end": {
              "line": 10,
              "character": 21
            }
          }
        ]
      },
      {
        "stableId": 5,
        "parentKind": 3,
        "kind": 25,
        "storage": 1,
        "ranges": [
          {
            "start": {
              "line": 8,
              "character": 25
            },
            "end": {
              "line": 8,
              "character": 26
            }
          },
          {
            "start": {
              "line": 9,
              "character": 4
            },
            "end": {
              "line": 9,
              "character": 5
            }
          }
        ]
      },
      {
        "stableId": 4,
        "parentKind": 0,
        "kind": 16,
        "storage": 0,
        "ranges": [
          {
            "start": {
              "line": 8,
              "character": 7
            },
            "end": {
              "line": 8,
              "character": 10
            }
          }
        ]
      },
      {
        "stableId": 0,
        "parentKind": 0,
        "kind": 7,
        "storage": 0,
        "ranges": [
          {
            "start": {
              "line": 1,
              "character": 7
            },
            "end": {
              "line": 1,
              "character": 17
            }
          },
          {
            "start": {
              "line": 2,
              "character": 2
            },
            "end": {
              "line": 2,
              "character": 12
            }
          },
          {
            "start": {
              "line": 8,
              "character": 11
            },
            "end": {
              "line": 8,
              "character": 21
            }
          },
          {
            "start": {
              "line": 10,
              "character": 4
            },
            "end": {
              "line": 10,
              "character": 14
            }
          }
        ]
      }
    ]
  }
}
```

**Comment by autozimu** [comment]
For nvim, the API `nvim_buf_add_highlight` might be a good fit in this case. And for vim, there isn't a proper way to do it as far as I know.

**Comment by MagBad** [comment]
For C++  on Neovim it's possible to use [chromatica](https://github.com/arakashic/chromatica.nvim) which basically does the requesting task. The issue is also related to #383 respectively.

**Comment by martskins** [comment]
I'll close this one as semantic highlighting is now supported.
