### ISSUE TITLE
Consider renaming functions and variables to match vim convention

### ISSUE THREAD

**Issue by euclio** [autozimu/LanguageClient-neovim#3]
Generally plugins use snake case for configuration variables and functions (`g:language_client_server_commands`) and `language_client#textDocument#hover()`.

**Comment by autozimu** [comment]
The rationality behind the current scheme is that I am going to use the prefix `LanguageClient` sort of like namespace. All variables, commands and functions will have the same prefix as project name.

Secondly, if I remember correctly, I tried using `#` as separator in the very beginning, but didn't work since these commands/functions are exported by neovim-python plugin decorators.

Besides, changing names at this stage will causes needless confusion and frustration for existing users.

I'm sorry if these decisions break vim convention or causing trouble for aesthetic purpose, but I am going to stick with it as it is right now.
