### ISSUE TITLE
[Suggestion] change camelCase to snake_case

### ISSUE THREAD

**Issue by HerringtonDarkholme** [autozimu/LanguageClient-neovim#33]
This is just a suggestion.

Python promotes snake_case rather than camelCase in this repo.

If snake_case is adopted, more devs can contribute idiomatic and pythonic code to this.

**Comment by autozimu** [comment]
Thanks.

Some of the function names like `textDocument_hover` is mimic the protocol method `textDocument/hover`, which also make it simple to executing method from server request, for example `textDocument/publishDiagnostics` will be mapped directly to `textDocument_publishDiagnostics`. Also, names like `text_document_publish_diagnostics` loses the original groupings. I'd like this part keep unchanged.

As for other internally used functions like `asyncCommand`, I will accept PRs for changing it to `async_command`. (But I won't make the changes myself due to short of time.)

**Comment by purpleP** [comment]
@autozimu It actually passes tests now, there are only linter errors now. I fixed them in second commit. Not all of them were mine, so not sure whether or not I should have done that.

**Comment by autozimu** [comment]
Resolved in https://github.com/autozimu/LanguageClient-neovim/commit/023ba139a86434205b3fd1c33bafa874e04404dd
