### ISSUE TITLE
workspace/didChangeWatchedFiles

### ISSUE THREAD

**Issue by autozimu** [autozimu/LanguageClient-neovim#347]
Quote from @vorner,

> The workspace/didChangeWatchedFiles would be pretty nice, as it seems it is missing for a real use case: rust-lang-nursery/rls#546. The RLS uses it to rebuild the full dependency graph when the Cargo.toml manifest changes.

**Comment by gvolpe** [comment]
Hi, I'm interested in seeing this working and came here to offer my help (though I have not experience in `Rust`). 

According to the [protocol](https://microsoft.github.io/language-server-protocol/specification#workspace_didChangeWatchedFiles) the client is responsible for sending a watch files notification.

Is there any work in progress on this or somebody looking at it? Thanks.

**Comment by autozimu** [comment]
No progress yet, at least from my side.

**Comment by Vigilans** [comment]
Just a question...does current implementation of watcher-registering supports globs like `**/*.ext`?:

https://github.com/autozimu/LanguageClient-neovim/blob/bfa0c0c883cc648d92cef4bc3fcafa21775a94eb/src/language_server_protocol.rs#L2040-L2046

It seems that `notify` [does not support glob pattern yet](https://github.com/autozimu/LanguageClient-neovim/blob/bfa0c0c883cc648d92cef4bc3fcafa21775a94eb/src/language_server_protocol.rs#L2040-L2046), and the code above just handles cases when `**` is placed at the end of a pattern...

Commit https://github.com/rust-lang/rls/commit/5d3665d611ab033c7b571ef894c0271fd16df28b unrolled the glob pattern, saying that it's due to glob crate problem, but I have no idea where this crate is used...

**Comment by autozimu** [comment]
> where this crate is used

the glob pattern is used in this client side.

**Comment by Vigilans** [comment]
Oh, what I mean is that I have no idea where the `glob` crate is used in this client side, because the only reference of cargo dependency `glob` is in `util::get_rootpath`:

https://github.com/autozimu/LanguageClient-neovim/blob/ec933531b207c7c46633d3bf604951d9dddf7eb2/src/utils.rs#L31-L35

instead of registering `didChangeWatchedFiles` capability.

So I have the question that whether `watch(w.glob_pattern.trim_end_matches("**")` will behave as expected when `w.glob_pattern` is for example `**/Cargo.toml` or `**/*.rs`, because it seems that `notify` does not support a glob pattern yet (maybe I am wrong here)...

Sorry for that I am not familiar with vim to test it myself, I use vscode and is investigating the `didChangeWatchedFiles` related issues.

**Comment by autozimu** [comment]
Sorry, I meant  the glob pattern (`Cargo.{toml,lock}`), not the glob create, is being parsed and used in this client.

No, if the glob patter is something like `**/Cargo.toml`, it won't be supported in this client.
