### ISSUE TITLE
Completion usage

### ISSUE THREAD

**Issue by Limeth** [autozimu/LanguageClient-neovim#39]
I use `deoplete` for auto-completion.
What's the preferred way of making it use `LanguageClient_textDocument_completion` as the source? Eg. I would like deoplete do display a window with suggestions in insert mode whenever possible.
Should I keep or uninstall `racer`?

**Comment by autozimu** [comment]
Normally, you don't need to do anything.

When you have both deoplete and this plugin installed and running, deoplete will add this plugin as a source and merge the completion results into the list.

From my own experience, it's better to keep `racer` there, as racer is more reliable and performant at the moment, and these two can coexist very well. When you see a list of completions, the one with `[LC]` is coming from this plugin, the one with `[racer]` coming from racer.

**Comment by Limeth** [comment]
I can't tell whether I am getting the completions from the RLS. What can I expect from its functionality? I can't see any completions with `[LC]`, all I'm seeing is `[racer]`, `[M]` and `[~]`. Maybe Racer is still more sophisticated and is overriding the results from LC?

**Comment by autozimu** [comment]
If both this plugin and racer returns the same result, the item from this plugin will trump over the one from racer.

So what you've described is deoplete is not playing well with this plugin. Please bear with us a moment, as deoplete just added async completion support weeks ago, and this plugin is making use of the feature. At the same time, I will try identify the described issue.

**Comment by HerringtonDarkholme** [comment]
Why is out of sync will be problem? Is this caused specifically by the racer completion?

**Comment by autozimu** [comment]
Before the referenced commit, I noticed a race condition between didChange notification and completion request.

For instance, when typing
```
te<CURSOR>
```
and trying to send the completion request, from the point of view of this plugin/rls, the text content is
```
t
```
which obviously is incorrect.

I didn't go into too much details, but I believe the situation was caused by the fact that event handlers are not guaranteed to execute in specific order. When user keeps typing, it will trigger two events, one is this plugin didChange, the other is deoplete, which in turn calls in this plugin for completion if necessary. And the order of execution is not guaranteed.

Also note, didChange notofications are still throttled and performance is not affected by the referenced commit, as for every change, there will be at most one notification send to server even if the didChange function is called multiple times, as it is guarded by [change detection](https://github.com/autozimu/LanguageClient-neovim/blob/master/rplugin/python3/LanguageClient/LanguageClient.py#L734).

**Comment by autozimu** [comment]
Racer has no confliction with this plugin.

**Comment by HerringtonDarkholme** [comment]
Thanks for your patient explanation!

**Comment by HerringtonDarkholme** [comment]
Just as a side note, deoplete seems to do throttling for async completer.

https://github.com/Shougo/deoplete.nvim/blob/master/doc/deoplete.txt#L194-L204
