### ISSUE TITLE
More doc on the settings.json ?

### ISSUE THREAD

**Issue by teto** [autozimu/LanguageClient-neovim#460]
Just wanted to request some more featurefull examples/explanation on the settings.json used by LanguageClient_loadSettings. :h LanguageCLient.txt is pretty scarce on the topic.
I set the path to:
`let g:LanguageClient_loadSettings=$XDG_CONFIG_HOME."/nvim/settings.json"`
(btw having the default adjusting for nvim path would be neat too (next release 0.3 has `stdpath('config')` which works across platforms).
Is the syntax LanguageClient-neovim specific ? if not refer to the official doc else put some example in the help please.
I use
```
{
    "pyls": {
        "plugins": {
            "pyflakes": {
                "enabled": false
            },
            "pydocstyle": {
                "enabled": false
            }
        }
    }
}

```
but I get 
```
||   File "/nix/store/811vahmvwab4i2q5mhrxyvdp3yv0fhfd-python3-3.6.5-env/lib/python3.6/json/__init__.py", line 354, in loads
||     return _default_decoder.decode(s)
||   File "/nix/store/811vahmvwab4i2q5mhrxyvdp3yv0fhfd-python3-3.6.5-env/lib/python3.6/json/decoder.py", line 339, in decode
||     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
||   File "/nix/store/811vahmvwab4i2q5mhrxyvdp3yv0fhfd-python3-3.6.5-env/lib/python3.6/json/decoder.py", line 355, in raw_decode
||     obj, end = self.scan_once(s, idx)
|| json.decoder.JSONDecodeError: Invalid control character at: line 1 column 64 (char 63)

```
with d0133bffd5c1d31f624f3f5f4f544d95ab4f7c4c and neovim 0.2.2

**Comment by autozimu** [comment]
Each language server almost defines its own way of specifying some parameters. For example, pyls seems using cfg files instead of json settings file, https://github.com/palantir/python-language-server#configuration

That's why I believe user should resort to language server official homepage for how to configure the server, rather than trying to document each and every of them inside this plugin, which is redundant and getting outdated easily.

Of course, if you find out how to configure pyls, it's always welcome to share it in wiki, https://github.com/autozimu/LanguageClient-neovim/wiki

**Comment by autozimu** [comment]
BTW, I don't know how the exception is triggered. Might be a bug of either side.

If you need my help for triaging it, please follow issue template to fill out necessary info.
