### ISSUE TITLE
First jump back from definition requires two C-o

### ISSUE THREAD

**Issue by LukaK** [autozimu/LanguageClient-neovim#485]
## Summary

Hello and thank You for maintaining the plugin. I have a question regarding jumping to definition. When I jump to definition I need to press C-o two time to come back if jumping changes files. First time jump is to the beginning of the file and second time back to the place of origin.

This only happens when I jump back the first time. That is if i jump to second file and then from that file jump again to some third file i need to press C-o  C-o to get to the second file and then C-o again to come back to the first file. The same holds with pyls and cquery servers.

## Reproduction
- neovim/vim version (`nvim --version` or `vim --version`): v0.3.0
- This plugin version (`git rev-parse --short HEAD`): f9a24af
- This plugin's binary version (`bin/languageclient --version`):0.1.91
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-init.vim]):
[minimal_init.txt](https://github.com/autozimu/LanguageClient-neovim/files/2128446/minimal_init.txt)

- Language server link and version: pyls (0.19.0-1), cquery (0.97)

**Comment by snapbug** [comment]
I got annoyed by this today as well, I did a bit of digging, and it's because the jump to definition is defined as first edit the file, and then jump to the lines location.

See [lines 846-847 of languageclient.rs](https://github.com/autozimu/LanguageClient-neovim/blob/9c5f2d1212a686936abfc601c44616d7578e5083/src/languageclient.rs#L846-L847), and 853-854 same file.

I don't speak rust enough to issue a pull request to fix this, but in neovim command speak, instead of `:e <filename> | execute 'normal <line>G'`, instead do `:e +<line> <filename>`, which opens the file at that line and removes the extra entry from the jump list.

**Comment by autozimu** [comment]
Thanks for pointing out `:e +num`. But I believe that only covers line position, column position cannot be specified following the same way.

**Comment by snapbug** [comment]
True enough, it doesn't.

I had a look, and the `+cmd` will accept any command, and there's a `cursor` function that can place the cursor anywhere. `:e +call\ cursor(<line>, <col>) <filename>` does the trick, although the column is really a byte count, which, probably isn't, but may be an issue?
