### ISSUE TITLE
multi filetype binding not working for the language server.

### ISSUE THREAD

**Issue by bmustiata** [autozimu/LanguageClient-neovim#526]
## Summary

In vim it's possible to have mutliple filetypes for the same buffer. (ie. `X_python.python`, or simpler `css.js.html`), and only the last one is used for syntax highlighting.

The language client will only trigger the first time when the file is opened, and won't work while editing. Changing the filetype manually W/As the issue.

## Reproduction
- neovim/vim version (`nvim --version` or `vim --version`):
NVIM v0.2.2
- This plugin version (`git rev-parse --short HEAD`):
736bbdf
- This plugin's binary version (`bin/languageclient --version`):
languageclient 0.1.101
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-init.vim]):
```vim
set hidden

let g:LanguageClient_serverCommands = {
    \ 'X_python.python': ['pyls'],
    \ 'X_python': ['pyls'],
    \ 'python': ['pyls'],
    \ }
```
- Language server link and version:
- Steps to reproduce the issue from clean state
    1. edit a new file named test.py
    2. set the filetype manually to: X_python.python: `:set filetype=X_python.python`
    3. try doing changes
- Logs (Paste or attach log file content):
none

## Current Behavior
Changes are not being validated with the language server.

## Expected Behavior
Changes should be validated against the language server. Using the last language name, that is also used for the syntax highlighting is ok imho. So having a filetype of `X_python.python` should call the language server for `python`.

> Please understand the more detailed information provided, the sooner a issue
could be resolved. Low quality bug reports might be closed directly.)

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting
[min-init.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-init.vim

**Comment by autozimu** [comment]
This plugin depends on filetype to find associated language server.

In your case, the filetype initially is python, so a python language server started for that buffer. Then the buffer filetype was changed to X_python.python. Note at this point, no language server automated started for this filetype X_python.python. All subsequent changes are not handled because no language server is running for the specific type.

There are ways to resolve this
1. Use `autocmd BufRead *.py setlocal filetype=X_python.python` so that filetype is specified before language server is started.
1. After changing filetype, manually start language server with `:LanguageClientStart`
