### ISSUE TITLE
Restart language servers when they crash

### ISSUE THREAD

**Issue by tbodt** [autozimu/LanguageClient-neovim#774]
## Is your feature request related to a problem? Please describe.
I'm running into a bug in clangd that causes it to crash pretty frequently while I edit.

## Describe the solution you'd like
There should be an option to automatically restart a language server that crashes (after printing a message saying it crashed, of course). I think it would also make sense for this to be the default.

## Describe alternatives you've considered
I'm trying to get the clangd bug fixed, but that might take a bit.

**Comment by afnanenayet** [comment]
As an addendum, it might be fruitful to have some sort of metering on this. Say you space out restarts, so you restart after 1 second after the first crash, having the restart time increase after subsequent crashes, or some sort of limit on how many times the server gets restarted.

I'm thinking of a scenario where a langserver just keeps constantly crashing and getting restarted, which could be an issue.

**Comment by dylanirlbeck** [comment]
I second this feature request!

I think a nice alternative would be a command you can call to restart the language server --- say `LanguageClient_restart()`. Then you could just remap a key to this function. Just a thought.

**Comment by loonies** [comment]
Yes please - a command for restarting the server.

It happens to me almost every time due to bug/crash during a debugging session - so annoying.

**Comment by ulidtko** [comment]
+1 on this from me.

I've tried emulating it via `map <Leader>r :LanguageClientStop<CR>:LanguageClientStart<CR>` — but that behaves racy, doesn't work. `E900: invalid channel id` appears frequently.

Mild caution for the implementer: please make sure to employ [exponential backoff][] when doing the restarts. The reason is: not all error-exits of the LSP server are crashes due to bug (plus, many of those won't be "cured" by restart — so, try to avoid making a crash loop) — in my case, the LSP server often gets too big appetite for RAM, and gets **OOM-killed** by the system (to prevent system stall).

It's a PITA that instead of simply hitting `\r` to bring it back up, I have to restart whole NVim.

[exponential backoff]: https://en.wikipedia.org/wiki/Exponential_backoff

**Comment by martskins** [comment]
Closing via #1113
