### ISSUE TITLE
Support additionalTextEdits field of CompletionItem

### ISSUE THREAD

**Issue by euclio** [autozimu/LanguageClient-neovim#85]
This is used by the Java language server to supply automatic imports on completion.

It should only edit the document once the completion is actually selected.

**Comment by autozimu** [comment]
Completion is handled by deoplete or NVM. I can definitely make a change in this plugin to pass down additionalTextEdits.

The bigger part of change will need to be done on deoplete or NVM part though.

**Comment by euclio** [comment]
According to the linked deoplete issue, Shougo would rather have the additional edits performed with the `CompleteDone` autocmd than in deoplete itself.

**Comment by DeltaEvo** [comment]
I'm trying to implement this and snippets support by using `CompleteDone` event, but i have some issues with this. 
Like @Shougo said this cause issues with other plugins because I can't assume that the completion came from LanguageClient.
I have some ideas but I don't like them:
-  If plugin is deoplete i can parse from menu attribute
-  Add some recognisable characters in some fields for the completion item

I think the best for this feature is that deoplete and ncm add a global variable containing the source name for the last completion but i don't know if it's possible ( hello @roxma ) ?

**Comment by autozimu** [comment]
It's also my conern.

Alternatively, it could be done by making PR for deoplete and NCM.

**Comment by autozimu** [comment]
This plugin has exposed enough information and function to achieve this feature.

The extra integration work should be done and tracked at completion framework side. e.g., https://github.com/roxma/nvim-completion-manager/issues/130
