### ISSUE TITLE
Flag for disabling diagnostics sorting

### ISSUE THREAD

**Issue by tdroxler** [autozimu/LanguageClient-neovim#916]
## Is your feature request related to a problem? Please describe.

I noticed that the diagnostics I send from my server were not in the same order in my quickfix list. I found here: https://github.com/autozimu/LanguageClient-neovim/blob/next/src/language_server_protocol.rs#L1926 that the diagnostics are now sorted. I'm wondering if it's the role of the client to sort them? Anyway I suppose you had good reasons to do it, so I was thinking of a flag to disable the sorting.

## Describe the solution you'd like

Having a flag to enable/disable the sorting of the diagnostics, to be able to have them in the same order as sent by the server.

## Describe alternatives you've considered
I have currently sadly moved back to a prior commit 

Thx a lot, cheers

**Comment by autozimu** [comment]
The reason diagnostics list is sorted is that one line might have multiple diagnostics and I figured high severity diagnostics should triumph lower ones during highlighting.

The problem here is that I probably got it wrong about when to kick off this sorting. You're right that the client shall preserve the diagnostic list order while presenting in quickfix etc.

**Comment by autozimu** [comment]
I will see if I can get time to create a fix soon.

**Comment by tdroxler** [comment]
Thx a lot
