### ISSUE TITLE
Allow code action without additional plugin

### ISSUE THREAD

**Issue by A1Liu** [autozimu/LanguageClient-neovim#995]
## Is your feature request related to a problem? Please describe.

I'd like to be able to use code action without installing FZF.

## Describe the solution you'd like

A numbered list menu similar to the context menu displayed in `LanguageClient_contextMenu()` .

**Comment by ipkiss42** [comment]
An option could be to leverage the new [vim-clap](https://github.com/liuchengxu/vim-clap), which provides a pretty nice user experience. There is already an integration with coc.nvim: https://github.com/vn-ki/coc-clap.

**Comment by martskins** [comment]
I think that would defeat the point @ipkiss42 , if I understand correctly the idea would be to offer this capability without requiring the user to have any particular plugin installed.

I think we could use `inputlist` for that, that's what `contextMenu` uses too, but it's a rather involved change.

**Comment by ipkiss42** [comment]
That's fair.

My point was more that LSP plugins tend to come up with their own ways of handling lists (among other things), instead of keeping that as an orthogonal concern which could be solved by a different number of UIs and tools.

In other words, while removing `fzf` as required dependency would be good, any hardccded replacement would be similarly limiting for users. It's impossible to come up with a solution that satisfies everybody, so IMHO the focus should be on making it easy to integrate with other ways to manipulate lists (such as `vim-clap`, `Unite`, `fzf` and others). It's fine to have your own implementation, but please keep interoperability in mind :)

**Comment by runiq** [comment]
It's already possible to get 'raw' code actions via `runSync()`: `:call LanguageClient_runSync('LanguageClient#textDocument_codeAction', {})`. You can shove that into vim-clap or whatever else you desire. Same for code locations (i.e. references, document/workspace symbols, etc.). The only thing that's not exposed right now are code lenses.

I've written about a similar plan in https://github.com/autozimu/LanguageClient-neovim/issues/1002#issuecomment-635473939.

**Comment by martskins** [comment]
This should now be possible as of #1059. So I'll close this one, but feel free to re-open if any other issues arise.

**Comment by ipkiss42** [comment]
Thanks, it's working great.

Note however that the help for `g:LanguageClient_selectionUI` still says:

```
Default: If fzf is loaded, use "fzf", otherwise use "location-list".                                                                                                                          
Valid options: "fzf" | "quickfix" | "location-list"                                                                                                                                           
```
